### PR TITLE
initial commit for the species list tool

### PR DESCRIPTION
**Pull request by sanderpick**
WIP. WIP. WIP.

I wanna get this up for some convo. Right now this thing is just logs a map click event ... next step is to execute the species list search. The results of that search can be passed to a list view (that uses a modal display) ... and off we go from there.

### CODE REVIEW

**Comment by tomauer** [comment]
Ok guys, I took a stab at working from where Sander left off to getting the query request made and the results back.

There are a few UI pieces to still wire together, but most of all I'm interested to learn where to subscribe for the result event and start building the list display.

**Comment by eightysteele** [comment]
@tomauer awesome dude. if you can push your latest to this branch, sander and i can show where to subscribe and starting building the list display.

**Comment by tomauer** [comment]
That's all I've got for right now. Let's go from here.

**Comment by tomauer** [comment]
Can we keep moving on this? I think it's on the top of my winding down list.

Do you want more code from me before we keep going?

**Comment by sanderpick** [comment]
Hey guys ... sorry for the delay in response. I caught a bug :( 

I did some work on the species results list modal this morning .. just pushing to save really ... more later today.

**Comment by eightysteele** [comment]
Thanks man, and noooo worries about the delay. And damn, hope you are
feeling better. It's actually good timing because Tom is taking another job
in a few months and this is now his biggest dev priority.

**Comment by tomauer** [comment]
Hey Sander, hope you're healthy in the New Year.

I'm back online and would like to get moving on this again. Let me know where I can pick up.

**Comment by sanderpick** [comment]
Hey Tom, I'm spinning up on this now ... goal is to get the basics of the list view in place, which would be a good point to have you guys pick up again. Thanks for your patience! I'm healthy again, finally. Happy New Year!

**Comment by sanderpick** [comment]
I made some good progress on porting the list view over ... more tonight.

**Comment by eightysteele** [comment]
Sick dude, thanks so much. Let me know where it's helpful to jump in.

**Comment by sanderpick** [comment]
Hey guys, I added the remainder of the list view. Next up are the other tabs:
- Images
- IUNC
- Download

@tomauer, does this feel like a good place to jump in?

**Comment by tomauer** [comment]
I think it is a good place. Can you give me a quick run through of how you've set it up?

**Comment by tomauer** [comment]
I've done a small bit to connect the download button. I wouldn't mind feedback on use of conditional HTML template and use of the model to accomplish this, to make sure I'm following the framework. Otherwise, I'll keep moving.

**Comment by sanderpick** [comment]
Yep yep ...

The main additions are:
- Species List view (w/ corresponding template)
  - subscribes to results from the Query widget
  - inits the dialog and addes all UI events
- Species List Row view (w/ corresponding template)
  - not much going on here, events are added by the parent (the List view ^)
- Species List model (the data from each result)
  - initializes by processing new variables (logic is self-contained)
- Species List collection
  - after all the models have initialized, do some extra processing of the data here

The main thing to see here is that each row in the table is placed by the list template (public/js/templates/lists/species.html) in a loop. We can add some more HTML in there to build the other tab contents as well ... we'll need to get a little creative there :) Since building this content will require running some more loops over the collection models (looking at the original imp.), we may be best suited creating another method in the list view to build that stuff, then call it after this.collection.process(), but before render(). Then, we can attach that new data (to build the template) to the collection before rendering.

If that is terribly confusing ... I can stub something out.

**Comment by tomauer** [comment]
Makes sense. Take a look at the bit I did for the download and I'll keep moving on IUCN.

**Comment by tomauer** [comment]
One spot I'm stuck on is loading the Google Visualization library. It in the old arch it was done this way:

<script type="text/javascript" src="https://www.google.com/jsapi"></script>

<script type="text/javascript">
    google.load("visualization", "1", {packages:["corechart"]});
</script>

I tried going through /js/libs/google/maps/load.js but it seems that the jsapi dependency isn't there AND I have no idea what to do with load.js.

**Comment by sanderpick** [comment]
checking ...

**Comment by sanderpick** [comment]
@tomauer, I'll have to take another look tonight ... I'm getting pulled into too many directions at the moment.

**Comment by sanderpick** [comment]
Okay, I played with this for awhile .. tried the [autoloading feature](https://developers.google.com/loader/#AutoLoading) of the google jsapi, but it was surprisingly really slow ... like 8 secs to load maps and the viz libs. So, just loading maps and the viz lib separately (in parallel) ... , then grab the cartolib.

**Comment by tomauer** [comment]
I'm battling a bug myself now, so I'll take a look at this Tuesday or Wednesday.

**Comment by eightysteele** [comment]
Hope you feel better dude!

**Comment by tomauer** [comment]
That worked. Thanks, Sander. I should be able to wrap up the species list tool port tomorrow.

**Comment by tomauer** [comment]
Can there be only one RowView per ListView? I'm trying to use rows to generate the gallery images and want to use the same species list.

**Comment by tomauer** [comment]
Alright, I've got the image gallery working, but I don't think it quite fits the framework, especially in regards to generating the snippet of HTML for each image. I couldn't figure out how to reference another RowView, so I'd take some guidance here.

**Comment by tomauer** [comment]
Alright, most of the species list tool pieces have been ported. Some of the interactions with other widgets have been left out for now.

Where do we want to go from here? I may only have a week or two left, depending on when my wife pops.

**Comment by robgur** [comment]
Tom, can you connect with Brian Stucky (cc:ed here) and maybe walk him
through where you are with the UI?  I think that will prove to be a big
help getting him up to speed.  Might be good to walk Brian through not only
UI but code dev best practices for MOL.

**Comment by tomauer** [comment]
Will do. I've sent a couple email off.

**Comment by sanderpick** [comment]
@tomauer, maybe we can build out the other map widgets? We could merge this and start a new feature branch. 
Screen Shot 2013-01-10 at 7 03 18 PM
Screen Shot 2013-01-10 at 7 03 22 PM

**Comment by tomauer** [comment]
I'll get started on the layers widget next week, since I'm most familiar with that.

**Comment by tomauer** [comment]
Jeremy and I talked and I'm going to get started on the Dashboard widget, since he's working on the layers parts pretty heavily right now. If you guys want to merge this then I'll go ahead and get started on the dashboard.

**Comment by walterj** [comment]
Ok!

On Jan 14, 2013, at 10:02, "Tom Auer" <notifications@github.com<mailto:notifications@github.com>> wrote:

Jeremy and I talked and I'm going to get started on the Dashboard widget, since he's working on the layers parts pretty heavily right now. If you guys want to merge this then I'll go ahead and get started on the dashboard.

**Comment by jmalczyk** [comment]
Yeah let's do the dashboard port. Thanks Tom!

**Comment by tomauer** [comment]
@sanderpick Can I merge this and move on? I just didn't want to merge it if you still had stuff to push. I'd like to keep going on this.

**Comment by sanderpick** [comment]
@tomauer, oops .. I figured you had already ... most def!

**Pull request merged**
